SECTION A: Data Structures & Control Structures

1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
#Create list
lst = [10,20,30,40,50]

#Append
lst.append(60)
print("Append:", lst)

#Extend
lst.extend([70, 80])
print("Extend:", lst)

#insert
lst.insert(2, 25)
print("Insert:", lst)

#remove
lst.remove(30)
print("Remove:", lst)

#pop
lst.pop()
print("Pop:", lst)

#index
print("Index of 40:", lst.index(40))

#count
print("Count of 20:", lst.count(20))

#sort
lst.sort()
print("Sort:", lst)

#reverse
lst.reverse()
print("Reverse:", lst)

#clear()
lst.clear()
print("Clear:", lst)

Append: [10, 20, 30, 40, 50, 60]
Extend: [10, 20, 30, 40, 50, 60, 70, 80]
Insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
Remove: [10, 20, 25, 40, 50, 60, 70, 80]
Pop: [10, 20, 25, 40, 50, 60, 70]
Index of 40: 3
Count of 20: 1
Sort: [10, 20, 25, 40, 50, 60, 70]
Reverse: [70, 60, 50, 40, 25, 20, 10]
Clear: []


2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
# Create a tuple with 3 student names
students = ("Anash", "Shoeb", "Zeeshan" )

# Trying to change value
students[1] = "priya" # This will cause an error

TypeError: 'tuple' object does not support item assignment

What happens?
When we try to change the second element of the tuple, a TypeError occurs:

TypeError: 'tuple' object does not support item assignment

why:
This happens because a tuple is immutable, which means its elements cannot be changed after it is created. Python does not allow modification of tuple values, so any attempt to assign a new value to an existing index results in an error.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [5]:
s = {1, 2, 2, 3, 4, 4, 5}
print("set:", s)

set: {1, 2, 3, 4, 5}


 Output has no duplicates because set removes duplicates automatically

4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [7]:
d = {"name": "anash", "age": 22, "city": "Ranchi"}

# update age
d["age"] = 25

#add a new key
d["email"] = "anash@gmail.com"

print(d)

{'name': 'anash', 'age': 25, 'city': 'Ranchi', 'email': 'anash@gmail.com'}


5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [8]:
#store age in variable
age = 20 #you can change this value

#check if age is 18 or more
if age >= 18:
    print("You are eligible to vote.") #if condition is true
else:
    print("You are not eligible to vote.") #if condition is false

You are eligible to vote.


6.Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [9]:
#Store the marks in a variable
marks = 82  #you can change this value

#Check marks and print grade
if marks >= 90:
    print("Grade: A") #90 and above
elif marks >= 75:
    print("Grade: B") # 75 to 89
elif marks >= 50:
    print("Grade: C") #50 to 74
else:
    print("Grade: Fail") #below 50

Grade: B


7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [11]:
#Store number in a variable 
num = 5  #you can change this value

#Check if number is positive 
if num > 0:
    # If positive, check if it is even
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("The number is Zero")   # if number is 0
else:
    print("The number is Negative") #if number is less than 0

Positive but Odd


Section B: Numpy

8.Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [13]:
import numpy as np #import numpy

#Create a scalar
scalar = np.array(5)
print("Scaler:", scalar)

#Create a 1D array (1 to 5)
arr1D = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1D)

#Create a 2D array (2x3) with values 10 to 60
arr2D = np.array([[10, 20, 30],
                  [40, 50, 60]])
print("2D Array:\n", arr2D)

Scaler: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [14]:
import numpy as np #import numpy

#Create a 4x4 array with random integers from 0 to 100
arr = np.random.randint(0, 101, (4, 4))

print("4x4 Random Array:\n", arr)

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.4x4 Random Array:
 [[20  6 82 89]
 [60 63 56 83]
 [89  2 77 22]
 [41 84 80 31]]



10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [1]:
# Import required libraries
import numpy as np
import pandas as pd

# Step 1: Create a 2D NumPy array of shape (3x3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Step 2: Convert Numpy array into Pandas DataFrame
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

# Step 3: Display the DataFrame
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [10]:
# Import pandas
import pandas as pd

# Step 1: Create DataFrame
data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "Age": [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Chennai",
             "Delhi", "Mumbai", "Pune", "Delhi", "Chennai"],
    "Salary": [50000, 60000, None, 55000, 52000,
               None, 58000, 61000, 59000, None]
}

df = pd.DataFrame(data)

# Step 2: Info
print("DataFrame Info:")
df.info()

# Step 3: Describe
print("\nStatistical Summary:")
print(df.describe())

# Step 4: Select Name and City
print("\nSelected Columns (Name & City):")
print(df[["Name", "City"]])

# Step 5: Drop City column
df = df.drop("City", axis=1)

# Step 6: Fill missing Salary with mean
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

# Step 7: Remove duplicates
df = df.drop_duplicates()

# Final Output
print("\nFinal DataFrame after cleaning:")
print(df)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

Statistical Summary:
            Age        Salary
count  10.00000      7.000000
mean   25.50000  56428.571429
std     3.02765   4197.504928
min    21.00000  50000.000000
25%    23.25000  53500.000000
50%    25.50000  58000.000000
75%    27.75000  59500.000000
max    30.00000  61000.000000

Selected Columns (Name & City):
  Name     City
0    A    Delhi
1    B   Mumbai
2    C     Pune
3    D    Delhi
4    E  Chennai
5    F    Delhi
6    G   Mumbai
7    H     Pune
8    I    Delhi
9    J  Chennai

Final DataFrame after cleaning:
  Name  Age        Salary
0    A   21  50000.000000
1    B  